title: Fantasticweekend
description: Video gamezz
author: Fantasticweekend
github: https://github.com/fantasticweekend
about: Jeux et blog
disqus_shortname: fantasticweekend
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/fantasticweekend"

urls:
    - text: Lexique
      url: /about/
    - text: Gallerie des jeux
      url: /projects/
    - text: XML
      url: /feed.xml

url: "https://fantasticweekend.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
